[2024-06-16T20:35:49.636+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-06-16T20:35:49.747+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: Air_pollution_data_pipeline.validator manual__2024-06-16T20:20:35+00:00 [queued]>
[2024-06-16T20:35:49.774+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: Air_pollution_data_pipeline.validator manual__2024-06-16T20:20:35+00:00 [queued]>
[2024-06-16T20:35:49.775+0000] {taskinstance.py:2306} INFO - Starting attempt 3 of 6
[2024-06-16T20:35:49.812+0000] {taskinstance.py:2330} INFO - Executing <Task(_PythonDecoratedOperator): validator> on 2024-06-16 20:20:35+00:00
[2024-06-16T20:35:49.827+0000] {standard_task_runner.py:63} INFO - Started process 8708 to run task
[2024-06-16T20:35:49.839+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'Air_pollution_data_pipeline', 'validator', 'manual__2024-06-16T20:20:35+00:00', '--job-id', '897', '--raw', '--subdir', 'DAGS_FOLDER/main.py', '--cfg-path', '/tmp/tmp8blcdi6h']
[2024-06-16T20:35:49.846+0000] {standard_task_runner.py:91} INFO - Job 897: Subtask validator
[2024-06-16T20:35:50.003+0000] {task_command.py:426} INFO - Running <TaskInstance: Air_pollution_data_pipeline.validator manual__2024-06-16T20:20:35+00:00 [running]> on host 333385971b19
[2024-06-16T20:35:50.729+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='khalid' AIRFLOW_CTX_DAG_ID='Air_pollution_data_pipeline' AIRFLOW_CTX_TASK_ID='validator' AIRFLOW_CTX_EXECUTION_DATE='2024-06-16T20:20:35+00:00' AIRFLOW_CTX_TRY_NUMBER='3' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-06-16T20:20:35+00:00'
[2024-06-16T20:35:50.731+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-06-16T20:35:50.732+0000] {validate.py:11} INFO - stating data validation/transformation process
[2024-06-16T20:35:50.734+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-06-16T20:35:50.735+0000] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/baseoperator.py", line 401, in wrapper
    return func(self, *args, **kwargs)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/decorators/base.py", line 265, in execute
    return_value = super().execute(context)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/baseoperator.py", line 401, in wrapper
    return func(self, *args, **kwargs)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/operators/python.py", line 235, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/operators/python.py", line 252, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/validate/validate.py", line 14, in validator
    input_clean_data = pd.read_json(input_clean_data)
  File "/home/airflow/.local/lib/python3.10/site-packages/pandas/io/json/_json.py", line 791, in read_json
    json_reader = JsonReader(
  File "/home/airflow/.local/lib/python3.10/site-packages/pandas/io/json/_json.py", line 904, in __init__
    data = self._get_data_from_filepath(filepath_or_buffer)
  File "/home/airflow/.local/lib/python3.10/site-packages/pandas/io/json/_json.py", line 944, in _get_data_from_filepath
    self.handles = get_handle(
  File "/home/airflow/.local/lib/python3.10/site-packages/pandas/io/common.py", line 719, in get_handle
    if _is_binary_mode(path_or_buf, mode) and "b" not in mode:
  File "/home/airflow/.local/lib/python3.10/site-packages/pandas/io/common.py", line 1181, in _is_binary_mode
    return isinstance(handle, _get_binary_io_classes()) or "b" in getattr(
TypeError: argument of type 'method' is not iterable
[2024-06-16T20:35:50.750+0000] {taskinstance.py:1206} INFO - Marking task as UP_FOR_RETRY. dag_id=Air_pollution_data_pipeline, task_id=validator, run_id=manual__2024-06-16T20:20:35+00:00, execution_date=20240616T202035, start_date=20240616T203549, end_date=20240616T203550
[2024-06-16T20:35:50.777+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 897 for task validator (argument of type 'method' is not iterable; 8708)
[2024-06-16T20:35:50.822+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2024-06-16T20:35:50.941+0000] {taskinstance.py:3503} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-06-16T20:35:50.948+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
