[2024-06-16T17:49:26.532+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-06-16T17:49:26.576+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: Air_pollution_data_pipeline.validator manual__2024-06-16T17:44:53+00:00 [queued]>
[2024-06-16T17:49:26.589+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: Air_pollution_data_pipeline.validator manual__2024-06-16T17:44:53+00:00 [queued]>
[2024-06-16T17:49:26.590+0000] {taskinstance.py:2306} INFO - Starting attempt 3 of 6
[2024-06-16T17:49:26.608+0000] {taskinstance.py:2330} INFO - Executing <Task(_PythonDecoratedOperator): validator> on 2024-06-16 17:44:53+00:00
[2024-06-16T17:49:26.615+0000] {standard_task_runner.py:63} INFO - Started process 5216 to run task
[2024-06-16T17:49:26.621+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'Air_pollution_data_pipeline', 'validator', 'manual__2024-06-16T17:44:53+00:00', '--job-id', '512', '--raw', '--subdir', 'DAGS_FOLDER/main.py', '--cfg-path', '/tmp/tmpx2oyk5b5']
[2024-06-16T17:49:26.628+0000] {standard_task_runner.py:91} INFO - Job 512: Subtask validator
[2024-06-16T17:49:26.705+0000] {task_command.py:426} INFO - Running <TaskInstance: Air_pollution_data_pipeline.validator manual__2024-06-16T17:44:53+00:00 [running]> on host 333385971b19
[2024-06-16T17:49:27.128+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='khalid' AIRFLOW_CTX_DAG_ID='Air_pollution_data_pipeline' AIRFLOW_CTX_TASK_ID='validator' AIRFLOW_CTX_EXECUTION_DATE='2024-06-16T17:44:53+00:00' AIRFLOW_CTX_TRY_NUMBER='3' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-06-16T17:44:53+00:00'
[2024-06-16T17:49:27.130+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-06-16T17:49:27.132+0000] {validate.py:11} INFO - stating data validation/transformation process
[2024-06-16T17:49:27.182+0000] {logging_mixin.py:188} WARNING - /opt/***/dags/validate/validate.py:14 FutureWarning: Passing literal json to 'read_json' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
[2024-06-16T17:49:28.134+0000] {python.py:237} INFO - Done. Returned value was: yes
[2024-06-16T17:49:28.134+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-06-16T17:49:28.147+0000] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 474, in _execute_task
    raise AirflowException(
airflow.exceptions.AirflowException: Returned output was type <class 'str'> expected dictionary for multiple_outputs
[2024-06-16T17:49:28.152+0000] {taskinstance.py:1206} INFO - Marking task as UP_FOR_RETRY. dag_id=Air_pollution_data_pipeline, task_id=validator, run_id=manual__2024-06-16T17:44:53+00:00, execution_date=20240616T174453, start_date=20240616T174926, end_date=20240616T174928
[2024-06-16T17:49:28.173+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 512 for task validator (Returned output was type <class 'str'> expected dictionary for multiple_outputs; 5216)
[2024-06-16T17:49:28.199+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2024-06-16T17:49:28.236+0000] {taskinstance.py:3503} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-06-16T17:49:28.239+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
