[2024-06-19T20:32:15.590+0000] {scheduler_job_runner.py:843} ERROR - Executor reports task instance <TaskInstance: Air_pollution_data_pipeline.insert_into_db_table manual__2024-06-19T20:19:39+00:00 [queued]> finished (failed) although the task says it's queued. (Info: None) Was the task killed externally?
