[2024-06-16T17:21:39.224+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-06-16T17:21:39.273+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: Air_pollution_data_pipeline.validator manual__2024-06-16T17:21:16+00:00 [queued]>
[2024-06-16T17:21:39.289+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: Air_pollution_data_pipeline.validator manual__2024-06-16T17:21:16+00:00 [queued]>
[2024-06-16T17:21:39.290+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 6
[2024-06-16T17:21:39.313+0000] {taskinstance.py:2330} INFO - Executing <Task(_PythonDecoratedOperator): validator> on 2024-06-16 17:21:16+00:00
[2024-06-16T17:21:39.321+0000] {standard_task_runner.py:63} INFO - Started process 4477 to run task
[2024-06-16T17:21:39.326+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'Air_pollution_data_pipeline', 'validator', 'manual__2024-06-16T17:21:16+00:00', '--job-id', '479', '--raw', '--subdir', 'DAGS_FOLDER/main.py', '--cfg-path', '/tmp/tmp5nqmov49']
[2024-06-16T17:21:39.329+0000] {standard_task_runner.py:91} INFO - Job 479: Subtask validator
[2024-06-16T17:21:39.411+0000] {task_command.py:426} INFO - Running <TaskInstance: Air_pollution_data_pipeline.validator manual__2024-06-16T17:21:16+00:00 [running]> on host 333385971b19
[2024-06-16T17:21:40.052+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='khalid' AIRFLOW_CTX_DAG_ID='Air_pollution_data_pipeline' AIRFLOW_CTX_TASK_ID='validator' AIRFLOW_CTX_EXECUTION_DATE='2024-06-16T17:21:16+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-06-16T17:21:16+00:00'
[2024-06-16T17:21:40.053+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-06-16T17:21:40.054+0000] {validate.py:11} INFO - stating data validation/transformation process
[2024-06-16T17:21:40.094+0000] {logging_mixin.py:188} WARNING - /opt/***/dags/validate/validate.py:14 FutureWarning: Passing literal json to 'read_json' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
[2024-06-16T17:21:40.425+0000] {python.py:237} INFO - Done. Returned value was: ['Ammonia_NH_emissions', 'Black_carbon_BC_emissions', 'Carbon_monoxide_CO_emissions', 'Entity', 'Nitrogen_oxide_NOx', 'Non_methane_volatile_organic_compounds_NMVOC_emissions', 'Organic_carbon_OC_emissions', 'Sulphur_dioxide_SO_emissions', 'Year']
[2024-06-16T17:21:40.426+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-06-16T17:21:40.439+0000] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 474, in _execute_task
    raise AirflowException(
airflow.exceptions.AirflowException: Returned output was type <class 'list'> expected dictionary for multiple_outputs
[2024-06-16T17:21:40.443+0000] {taskinstance.py:1206} INFO - Marking task as UP_FOR_RETRY. dag_id=Air_pollution_data_pipeline, task_id=validator, run_id=manual__2024-06-16T17:21:16+00:00, execution_date=20240616T172116, start_date=20240616T172139, end_date=20240616T172140
[2024-06-16T17:21:40.464+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 479 for task validator (Returned output was type <class 'list'> expected dictionary for multiple_outputs; 4477)
[2024-06-16T17:21:40.502+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2024-06-16T17:21:40.537+0000] {taskinstance.py:3503} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-06-16T17:21:40.540+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
