[2024-06-16T16:04:45.521+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-06-16T16:04:45.742+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: Air_pollution_data_pipeline.generate_summary manual__2024-06-16T16:02:04+00:00 [queued]>
[2024-06-16T16:04:45.793+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: Air_pollution_data_pipeline.generate_summary manual__2024-06-16T16:02:04+00:00 [queued]>
[2024-06-16T16:04:45.794+0000] {taskinstance.py:2306} INFO - Starting attempt 2 of 6
[2024-06-16T16:04:45.860+0000] {taskinstance.py:2330} INFO - Executing <Task(_PythonDecoratedOperator): generate_summary> on 2024-06-16 16:02:04+00:00
[2024-06-16T16:04:45.885+0000] {standard_task_runner.py:63} INFO - Started process 1055 to run task
[2024-06-16T16:04:45.944+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'Air_pollution_data_pipeline', 'generate_summary', 'manual__2024-06-16T16:02:04+00:00', '--job-id', '167', '--raw', '--subdir', 'DAGS_FOLDER/main.py', '--cfg-path', '/tmp/tmp8r6p57cq']
[2024-06-16T16:04:45.958+0000] {standard_task_runner.py:91} INFO - Job 167: Subtask generate_summary
[2024-06-16T16:04:46.682+0000] {task_command.py:426} INFO - Running <TaskInstance: Air_pollution_data_pipeline.generate_summary manual__2024-06-16T16:02:04+00:00 [running]> on host 333385971b19
[2024-06-16T16:04:47.564+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='khalid' AIRFLOW_CTX_DAG_ID='Air_pollution_data_pipeline' AIRFLOW_CTX_TASK_ID='generate_summary' AIRFLOW_CTX_EXECUTION_DATE='2024-06-16T16:02:04+00:00' AIRFLOW_CTX_TRY_NUMBER='2' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-06-16T16:02:04+00:00'
[2024-06-16T16:04:47.568+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-06-16T16:04:47.572+0000] {summary_analysis.py:13} INFO - starting summary statistics of pollutants emission
[2024-06-16T16:04:47.578+0000] {summary_analysis.py:26} ERROR - error calculating pollutants summary statistics
Traceback (most recent call last):
  File "/opt/airflow/dags/statistical_analysis/summary_analysis.py", line 16, in generate_summary
    val_data = pd.read_json(val_data)
  File "/home/airflow/.local/lib/python3.10/site-packages/pandas/io/json/_json.py", line 791, in read_json
    json_reader = JsonReader(
  File "/home/airflow/.local/lib/python3.10/site-packages/pandas/io/json/_json.py", line 904, in __init__
    data = self._get_data_from_filepath(filepath_or_buffer)
  File "/home/airflow/.local/lib/python3.10/site-packages/pandas/io/json/_json.py", line 944, in _get_data_from_filepath
    self.handles = get_handle(
  File "/home/airflow/.local/lib/python3.10/site-packages/pandas/io/common.py", line 728, in get_handle
    ioargs = _get_filepath_or_buffer(
  File "/home/airflow/.local/lib/python3.10/site-packages/pandas/io/common.py", line 472, in _get_filepath_or_buffer
    raise ValueError(msg)
ValueError: Invalid file path or buffer object type: <class 'NoneType'>
[2024-06-16T16:04:47.583+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-06-16T16:04:47.584+0000] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/baseoperator.py", line 401, in wrapper
    return func(self, *args, **kwargs)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/decorators/base.py", line 265, in execute
    return_value = super().execute(context)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/baseoperator.py", line 401, in wrapper
    return func(self, *args, **kwargs)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/operators/python.py", line 235, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/operators/python.py", line 252, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/statistical_analysis/summary_analysis.py", line 16, in generate_summary
    val_data = pd.read_json(val_data)
  File "/home/airflow/.local/lib/python3.10/site-packages/pandas/io/json/_json.py", line 791, in read_json
    json_reader = JsonReader(
  File "/home/airflow/.local/lib/python3.10/site-packages/pandas/io/json/_json.py", line 904, in __init__
    data = self._get_data_from_filepath(filepath_or_buffer)
  File "/home/airflow/.local/lib/python3.10/site-packages/pandas/io/json/_json.py", line 944, in _get_data_from_filepath
    self.handles = get_handle(
  File "/home/airflow/.local/lib/python3.10/site-packages/pandas/io/common.py", line 728, in get_handle
    ioargs = _get_filepath_or_buffer(
  File "/home/airflow/.local/lib/python3.10/site-packages/pandas/io/common.py", line 472, in _get_filepath_or_buffer
    raise ValueError(msg)
ValueError: Invalid file path or buffer object type: <class 'NoneType'>
[2024-06-16T16:04:47.622+0000] {taskinstance.py:1206} INFO - Marking task as UP_FOR_RETRY. dag_id=Air_pollution_data_pipeline, task_id=generate_summary, run_id=manual__2024-06-16T16:02:04+00:00, execution_date=20240616T160204, start_date=20240616T160445, end_date=20240616T160447
[2024-06-16T16:04:47.738+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 167 for task generate_summary (Invalid file path or buffer object type: <class 'NoneType'>; 1055)
[2024-06-16T16:04:47.771+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2024-06-16T16:04:47.824+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
