[2024-06-18T11:22:05.948+0000] {scheduler_job_runner.py:843} ERROR - Executor reports task instance <TaskInstance: Air_pollution_data_pipeline.insert_into_db_table scheduled__2024-06-15T00:00:00+00:00 [queued]> finished (failed) although the task says it's queued. (Info: None) Was the task killed externally?
